name: Compile Python to Pyc
on:
  push:
    branches:
      - master # 可根据实际情况修改为需要监控的分支，如master等
    paths:
      - 'src/**/*.py' # 监控python_to_pyc.py文件的变化
jobs:
  compile:
    runs-on: ubuntu-latest # 根据Runner环境选择，一般可选windows-latest等
    steps:

      - name: Checkout code
        uses: actions/checkout@v4 # 检出仓库代码到Runner环境
        with:
          # 允许推送更改回仓库
          token: ${{ secrets.GHP_MCV9GHKSGD3GERNKTXIUQP6YMZ2ATV1EJC9C }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4 # 设置Python环境
        with:
          python-version: 3.8 # 根据代码所需Python版本填写，如3.8

      - name: Compile Python files
        run: python python_to_pyc.py # 运行你的编译脚本

      - name: Upload compiled files
        uses: actions/upload-artifact@v4  # 上传编译产物
        with:
          name: pyc-files
          path: ./pyc/  # 对应 Python 脚本里的输出目录

          #上传pyc文件
      - name: Commit and push pyc files
        run: |
          git config user.name gzy
          git config user.email zy_gao2024@163.com
          git add ./pyc/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-commit compiled pyc files"
            git push
          fi
